// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $container, $mallaCurricular;
    $container = $('.isotope-grid');
    $mallaCurricular = $('.malla-curricular');
    $mallaCurricular.children('li').addClass('malla-item');
    $container.children('li').addClass('isotope-item');
    $mallaCurricular.isotope({
      itemSelector: '.malla-item',
      layoutMode: 'fitRows'
    });
    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'fitRows'
      });
    });
  });

}).call(this);
