// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var myPlayer, playBtn, videoPlaying, videocover;
    videocover = document.getElementById('videocover');
    playBtn = $('.play-video');
    videoPlaying = false;
    if (videocover) {
      myPlayer = videojs('videocover');
      myPlayer.controls(false);
    }
  });

}).call(this);
