// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $breadcrumbs, $lastPath, $mainPath, $rootPath, absoluteURL, lastPath, locationArr, mainPath;
    $breadcrumbs = $('.breadcrumbs-custom');
    $rootPath = $breadcrumbs.find('.root-path');
    $mainPath = $breadcrumbs.find('.main-path');
    $lastPath = $breadcrumbs.find('.last-path');
    absoluteURL = window.location.href.split('/');
    absoluteURL.splice(absoluteURL.length - 1, 1);
    absoluteURL = absoluteURL.join('/');
    locationArr = window.location.pathname.split('/');
    mainPath = locationArr[locationArr.length - 2];
    lastPath = locationArr[locationArr.length - 1];
    $mainPath.attr('href', absoluteURL);
    $lastPath.attr('href', window.location.href);
    lastPath = lastPath.replace(/\..*/, '');
    mainPath = mainPath.replace(/[^a-z0-9]/gi, '');
    lastPath = lastPath.replace(/[^a-z0-9]/gi, ' ');
    $mainPath.find('span').text(mainPath);
    $lastPath.find('span').text(lastPath);
  });

}).call(this);
