// Generated by CoffeeScript 1.8.0
(function() {
  $(document).ready(function() {
    var $siteMenu, isIE, pgwBrowser;
    $siteMenu = $('.site-menu');
    $('.disable-anchors a').click(function(e) {
      e.preventDefault();
    });
    $('[data-href]').click(function(e) {
      var lastPath, locationArr, mainPath, pathObj;
      locationArr = window.location.pathname.split('/');
      lastPath = locationArr[locationArr.length - 1];
      mainPath = locationArr[locationArr.length - 2];
      pathObj = {};
      pathObj[mainPath] = lastPath;
      window.history.pushState(pathObj, '', lastPath);
      document.location.replace($(this).data('href'));
    });
    $('.menu-trigger').click(function(e) {
      e.preventDefault();
      $('.site-wrapper').toggleClass('menu-on');
      $('body').toggleClass('scroll-y-off');
    });
    $('#edit-submit.form-submit').addClass('atm-buscar');
    $('.language-link').addClass('atm-idiomas');
    pgwBrowser = $.pgwBrowser();
    console.log(pgwBrowser);
    isIE = pgwBrowser['browser']['group'] === 'Explorer' ? true : false;
    if (isIE) {
      $('.site-wrapper').addClass('ie');
      $('.site-menu').hide();
    }
  });

}).call(this);
